### PR TITLE
Add Thoth Search UI URL to response headers

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to https://github.com/thoth-station/user-api/issues/1721

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

Add Thoth Search UI URL to response headers in schema specification and user-api entrypoint.

### CODE REVIEW

**Review by fridex — APPROVED** [review]
nice, lgtm! 💯 👍🏻

**Comment by goern** [comment]
uuuh I like!! :heart: 

/approve

**Pull request merged**
