### PR TITLE
remove github app parameters

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies
Depends-On: https://github.com/thoth-station/messaging/pull/442
Depends-On: https://github.com/thoth-station/common/pull/1176
Fixes: https://github.com/thoth-station/user-api/issues/1454

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Remove parameters for github app

### CODE REVIEW

**Comment by pacospace** [comment]
Waiting for https://github.com/thoth-station/common/issues/1178

**Comment by pacospace** [comment]
Waiting for https://github.com/thoth-station/messaging/issues/445

**Review by fridex — APPROVED** [review]
lgtm, thanks! 👍🏻

**Pull request merged**
