### PR TITLE
List solved Python package versions

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/user-api/issues/1545

## This introduces a breaking change

- [x] No

## Description

Show only solved packages to users.

### CODE REVIEW

**Comment by fridex** [comment]
/unhold

Covered in https://github.com/thoth-station/user-api/pull/1547 as well.

**Comment by mayaCostantini** [comment]
lgtm :+1: 
/approve

**Comment by fridex** [comment]
> lgtm +1 /approve

/approve

**Comment by fridex** [comment]
All green. Merging to continue with work.

**Pull request merged**
