### PR TITLE
Fix message content

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Fixes:

```
Traceback (most recent call last):
  File "/opt/app-root/src/prepare.py", line 97, in <module>
    __name__ == "__main__" and main()  # type: ignore
  File "/opt/app-root/src/prepare.py", line 40, in main
    prepare_adviser(request_file_content)
  File "/opt/app-root/src/prepare.py", line 62, in prepare_adviser
    _prepare_application_stack(request_file_content)
  File "/opt/app-root/src/prepare.py", line 51, in _prepare_application_stack
    pipfile_content = request_file_content["application_stack"]["requirements"]
KeyError: 'application_stack'
```

**Comment by fridex** [comment]
/unhold
/assign @harshad16 PTAL

Looks operational.

**Review by harshad16 — COMMENTED** [review]
/lgtm 
thanks for adding

**Pull request merged**
