### PR TITLE
Expose schema metric

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/metrics-exporter/issues/529

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
Does it mean the alembic version will be updated each time there is done a request to user-api?

**Comment by pacospace** [comment]
> Does it mean the alembic version will be updated each time there is done a request to user-api?

I think every time the is a call it will be exposed again.

it should be a constant information as it should not change until we change user-api version

**Comment by fridex** [comment]
> > Does it mean the alembic version will be updated each time there is done a request to user-api?
> 
> I think every time there is a call it will be exposed again.
> 
> it should be a constant information as it should not change until we change user-api version

Yes, so I don't think this is something we want to do with each user request as it slows down user-api and also will not help with scaling. Doing this before a very first request should be good enough as the metric should stay constant (and kept in the memory).

**Comment by pacospace** [comment]
> > > Does it mean the alembic version will be updated each time there is done a request to user-api?
> > 
> > 
> > I think every time there is a call it will be exposed again.
> > it should be a constant information as it should not change until we change user-api version
> 
> Yes, so I don't think this is something we want to do with each user request as it slows down user-api and also will not help with scaling. Doing this before a very first request should be good enough as the metric should stay constant (and kept in the memory).

I moved it under `@application.before_first_request`

**Review by fridex — APPROVED** [review]
thanks! :+1:

**Pull request merged**
