### PR TITLE
Bump messaging module version

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by KPostOffice** [comment]
This will cause breakage.  0.7.13 is the last release before the confluent rework.  Deployment needs to be updated as well as some code. I will open a PR in user api and thoth-application

**Comment by fridex** [comment]
> This will cause breakage. 0.7.13 is the last release before the confluent rework. Deployment needs to be updated as well as some code. I will open a PR in user api and thoth-application

Cool, thanks for that! :+1:

**Comment by KPostOffice** [comment]
it actually may be fine because user-api messaging implementation was already "special". I will still make the changes so that it reflects new `thoth-messaging` implementation

**Comment by fridex** [comment]
The deployment fails on:

```
Failed to add operation for POST /api/v1/image/metadata
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/resolver.py", line 61, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/utils.py", line 111, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 73, in <module>
    if config_topic.protocol == "SSL":
AttributeError: 'MessageBase' object has no attribute 'protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/apis/abstract.py", line 209, in add_paths
    self.add_operation(path, method)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/apis/abstract.py", line 162, in add_operation
    operation = make_operation(
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/operations/__init__.py", line 8, in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/operations/openapi.py", line 128, in from_spec
    return cls(
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/operations/openapi.py", line 75, in __init__
    super(OpenAPIOperation, self).__init__(
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/operations/abstract.py", line 96, in __init__
    self._resolution = resolver.resolve(self)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/resolver.py", line 66, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: 'MessageBase' object has no attribute 'protocol'>
```

**Comment by fridex** [comment]
Closing as this was implemented by Kevin in #1195

**Pull request closed without merging**
