### PR TITLE
Delete Info

### PR DESCRIPTION
**Pull request by bissenbay**
Fixes: https://github.com/thoth-station/user-api/issues/573

### CODE REVIEW

**Comment by goern** [comment]
Can you link the pr that is adding it to management API?

**Comment by bissenbay** [comment]
> Can you link the pr that is adding it to management API?

@goern https://github.com/thoth-station/management-api/pull/233

**Comment by bissenbay** [comment]
@fridex This PR is also related to https://github.com/thoth-station/management-api/pull/233

**Comment by fridex** [comment]
@bissenbay is it still WIP?

**Comment by bissenbay** [comment]
> @bissenbay is it still WIP?

No

**Pull request merged**
