### PR TITLE
Use OpenShift as a naming service

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/openshift/openshift-restclient-python/pull/187
Depends-On: https://github.com/thoth-station/package-extract/pull/108
Depends-On: https://github.com/thoth-station/solver/pull/73
Depends-On: https://github.com/thoth-station/adviser/pull/46

### CODE REVIEW

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
@goern why is this in "Expected — Waiting for status to be reported" for so long?

**Pull request merged**
