### PR TITLE
remove origin from advise and prov digests

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

thoth-station/thoth-application#1112

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
what about all the other parameters for the digest? shouldn't be only the project (pipfile and pipfile.lock) + runtime environment + recommendation type (+ library_usage?) ? @KPostOffice @fridex 

```
            count=parameters["count"],
            limit=parameters["limit"],
            library_usage=parameters["library_usage"],
            source_type=source_type.upper() if source_type else None,
            dev=dev,
            debug=parameters["debug"],
            github_event_type=parameters["github_event_type"],
            github_check_run_id=parameters["github_check_run_id"],
            github_installation_id=parameters["github_installation_id"],
            github_base_repo_url=parameters["github_base_repo_url"],
            kebechet_metadata=parameters["kebechet_metadata"],
```

**Comment by fridex** [comment]
> what about all the other parameters for the digest? shouldn't be only the project (pipfile and pipfile.lock) + runtime environment + recommendation type (+ library_usage?) ? @KPostOffice @fridex
> 
> ```
>             count=parameters["count"],
>             limit=parameters["limit"],
>             library_usage=parameters["library_usage"],
>             source_type=source_type.upper() if source_type else None,
>             dev=dev,
>             debug=parameters["debug"],
>             github_event_type=parameters["github_event_type"],
>             github_check_run_id=parameters["github_check_run_id"],
>             github_installation_id=parameters["github_installation_id"],
>             github_base_repo_url=parameters["github_base_repo_url"],
>             kebechet_metadata=parameters["kebechet_metadata"],
> ```

I think the origin should be used when computing digest if an authenticated request is done to user-api as origin is used for parts of the workflow that are triggered on an authenticated request (cached files cannot be used here as they will not trigger reporting and such). I would expect the following logic adjustment:

1. if authenticated request - leave as is with the current logic in the master branch
2. if not authenticated request:
    1. remove origin when computing digest to cache
    2. if cache is hit, remove origin from the results as this origin does not need to be a valid origin and we do not want to reveal origin info to other users (e.g. user A did request, user B did request and uses cached results computed for user A - user B should not see the origin of A request)

**Comment by KPostOffice** [comment]
> > what about all the other parameters for the digest? shouldn't be only the project (pipfile and pipfile.lock) + runtime environment + recommendation type (+ library_usage?) ? @KPostOffice @fridex
> > ```
> >             count=parameters["count"],
> >             limit=parameters["limit"],
> >             library_usage=parameters["library_usage"],
> >             source_type=source_type.upper() if source_type else None,
> >             dev=dev,
> >             debug=parameters["debug"],
> >             github_event_type=parameters["github_event_type"],
> >             github_check_run_id=parameters["github_check_run_id"],
> >             github_installation_id=parameters["github_installation_id"],
> >             github_base_repo_url=parameters["github_base_repo_url"],
> >             kebechet_metadata=parameters["kebechet_metadata"],
> > ```
> 
> I think the origin should be used when computing digest if an authenticated request is done to user-api as origin is used for parts of the workflow that are triggered on an authenticated request (cached files cannot be used here as they will not trigger reporting and such). I would expect the following logic adjustment:
> 
>     1. if authenticated request - leave as is with the current logic in the master branch
> 
>     2. if not authenticated request:
>        
>        1. remove origin when computing digest to cache
>        2. if cache is hit, remove origin from the results as this origin does not need to be a valid origin and we do not want to reveal origin info to other users (e.g. user A did request, user B did request and uses cached results computed for user A - user B should not see the origin of A request)

In case (2) won't a cache hit which contains `origin` in the result be impossible?

**Comment by KPostOffice** [comment]
@fridex What if we created an "adviser" workflow which works with cached documents? Origin and a few other fields only matter in the context of the workflow right? On a cache hit we can supply the document ID and still run the rest of the workflow for the user just using the pre-computed result as the adviser output.  This way we can do what @pacospace suggested
> (what about all the other parameters for the digest? shouldn't be only the project (pipfile and pipfile.lock) + runtime environment + recommendation type (+ library_usage?) ?
This would maximize cache hits and minimize the amount of data we need to store.

**Comment by fridex** [comment]
> @fridex What if we created an "adviser" workflow which works with cached documents?

Not sure if this will help us. To run a workflow, we need cluster resources. By introducing another workflow we just postpone the issue as users will need to wait for the cached adviser workflow to finish. With the approach above, user-api directly reports back cached documents if they can be used based on the request supplied.

> Origin and a few other fields only matter in the context of the workflow right?

+1, hence the "authenticated" part of the workflow

> On a cache hit we can supply the document ID and still run the rest of the workflow for the user just using the pre-computed result as the adviser output. This way we can do what @pacospace suggested

I think an important aspect here is the user for which we are optimizing these cache hits. As of now, we don't need to optimize kebechet parts of the workflow. If kebechet hits user-api multiple times with the token supplied (authenticated workflow), all the fields are same for the request and hence the cache is hit respecting the cache lifetime configured. Let's do not overengineer this part, I think we do not have direct use case to optimize this now.

> > (what about all the other parameters for the digest? shouldn't be only the project (pipfile and pipfile.lock) + runtime environment + recommendation type (+ library_usage?) ?
> 
> This would maximize cache hits and minimize the amount of data we need to store.

Yes, this is exactly the case for unauthorized workflow as github specific parts, origin (and source_type) are not part of the input for computing digests to the cache. (note github parts are checked in "protected fields").

**Comment by KPostOffice** [comment]
> With the approach above, user-api directly reports back cached documents if they can be used based on the request supplied.

Cached adviser workflow would only be scheduled if the request is authenticated.
> Let's do not overengineer this part, I think we do not have direct use case to optimize this now.

Okay. We can do this eventually if we want. This optimization would be relevant to all users, authenticated requests can be stored without any project specific info so the advise can be reused by all.

**Comment by fridex** [comment]
Done in fridex/user-api#2 (part of https://github.com/thoth-station/user-api/pull/1354).

**Pull request closed without merging**
