### PR TITLE
Instantiate one adapter per wsgi worker

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by goern** [comment]
uh... nice :)

**Comment by goern** [comment]
@fridex is this still valid?

**Comment by bissenbay** [comment]
> @fridex is this still valid?

LGTM, WDYT @harshad16 ?

**Comment by harshad16** [comment]
I feel like this approach can cause an issue if the connection breaks, on the query to those endpoint would the graph connection be again with this approach?

**Comment by fridex** [comment]
> I feel like this approach can cause an issue if the connection breaks, on the query to those endpoint would the graph connection be again with this approach?

Good point :+1: We should check sqlalchemy and the connection pooling we are using to see if we could end up in an error state with a broken adapter.

**Comment by goern** [comment]
is this still relevant?

**Comment by fridex** [comment]
I think we are fine with the current approach. We might reconsider this if we hit some issues on the adapter side.

**Pull request closed without merging**
