### PR TITLE
List only enabled Python package indexes to users

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
> Build failed.
> 
> * [thoth-coala ](https://managesf.thoth-station.ninja/logs/45/645/80dabd05b7f68a6140a522348b6c6772bdd9f869/check/thoth-coala/a9ee608/) : FAILURE in 20s

not relevant

**Comment by goern** [comment]
> > Build failed.
> > 
> > * [thoth-coala ](https://managesf.thoth-station.ninja/logs/45/645/80dabd05b7f68a6140a522348b6c6772bdd9f869/check/thoth-coala/a9ee608/) : FAILURE in 20s
> 
> not relevant

this seems to be related to my latest update of the Zuul infra container images.

**Comment by goern** [comment]
regate

**Pull request merged**
