### PR TITLE
Do cache hit only for accepted requests

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## This Pull Request implements

Fixes access to the response data and performs cache hit metrics adjustment only based on the HTTP status code.

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace my wild guess, not tested

**Review by pacospace — APPROVED** [review]
lgtm! 💯

**Comment by pacospace** [comment]
> @pacospace my wild guess, not tested

this one also is needed to test https://github.com/thoth-station/user-api/pull/1372#issuecomment-814394510, but cluster is still down :/

**Pull request merged**
