### PR TITLE
Generalize _send_schedule_message method to consider authentication

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

Related-To: https://github.com/thoth-station/thoth-application/issues/1112

### CODE REVIEW

**Review by fridex — APPROVED** [review]
lgtm 👍🏻

**Review by KPostOffice — APPROVED** [review]

**Comment by pacospace** [comment]
finally ready!
```
# HELP thoth_user_api_adviser_authenticated_cache_hit_rate Thoth User API Adviser Authenticated cache hit rate
# TYPE thoth_user_api_adviser_authenticated_cache_hit_rate gauge
thoth_user_api_adviser_authenticated_cache_hit_rate 0.0
# HELP thoth_user_api_adviser_unauthenticated_cache_hit_rate Thoth User API Adviser Unauthenticated cache hit rate
# TYPE thoth_user_api_adviser_unauthenticated_cache_hit_rate gauge
thoth_user_api_adviser_unauthenticated_cache_hit_rate 0.0
# HELP thoth_user_api_provenance_checker_authenticated_cache_hit_rate Thoth User API Provenance Checker Authenticated cache hit rate
# TYPE thoth_user_api_provenance_checker_authenticated_cache_hit_rate gauge
thoth_user_api_provenance_checker_authenticated_cache_hit_rate 0.0
# HELP thoth_user_api_provenance_checker_unauthenticated_cache_hit_rate Thoth User API Provenance Checker Unauthenticated cache hit rate
# TYPE thoth_user_api_provenance_checker_unauthenticated_cache_hit_rate gauge
thoth_user_api_provenance_checker_unauthenticated_cache_hit_rate 7.0
```

**Pull request merged**
