### PR TITLE
Update base image version to latest

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to https://github.com/thoth-station/thoth-application/pull/2314#issuecomment-1029721353

## This introduces a breaking change

- No

## This should yield a new module release

- No

### CODE REVIEW

**Comment by goern** [comment]
/approve

@mayaCostantini could you create a new patch release after this is merged, and replace @fridex original PR https://github.com/thoth-station/thoth-application/pull/2314 and https://github.com/thoth-station/thoth-application/pull/2313

**Review by pacospace — APPROVED** [review]
👏🏼 thanks!

**Pull request merged**
