### PR TITLE
WIP: Add support for gRPC

### PR DESCRIPTION
**Pull request by fridex**
*TODO*:

- [ ] adjust deployment so that it serves gRPC server
- [ ] add TLS certificates for gRPC
- [ ] implement proto service with messages

### CODE REVIEW

**Comment by goern** [comment]
We should have a look at how OpenShift can help us with providing TLS certs, as they are only used intra-namespace we can skip dinner public root CA etc

**Comment by goern** [comment]
it's there a Trello card for this? @fridex

**Comment by fridex** [comment]
Yes - https://trello.com/c/vS9cLMdI/541-add-support-for-grpc-to-user-api

**Comment by goern** [comment]
sorry for spamming this PR

**Comment by goern** [comment]
is this still valid?

**Pull request closed without merging**
