### PR TITLE
Pin messaging to older version

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/user-api/issues/1133

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
As per discussion on the call. PTAL @KPostOffice

**Comment by fridex** [comment]
I'm still experiencing this issue when running locally:

```
pipenv run pip3 freeze | grep thoth-messaging
thoth-messaging==0.7.13
```

**Comment by KPostOffice** [comment]
I found the issue:
https://github.com/thoth-station/user-api/blob/e9a86c41723fad38fbc4bcd11a19e3b32ae4d423/thoth/user_api/api_v1.py#L73

this line needs to be replaced with:
```
config_topic.protocol == "SSL"
```

**Pull request closed without merging**
