### PR TITLE
Downgrade `flask` to `<=1.0.0`

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to #1701 

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

See https://github.com/thoth-station/user-api/issues/1701#issuecomment-1061512890
It looks like `flask` in version `<=1.0.0` does not require `jinja2 <3.0` which is incompatible with the implementation of User API.

The requirement `flask==1.1.4` was introduced as a hotfix for this issue: https://github.com/thoth-station/management-api/issues/762 because of the following error:
```
ModuleNotFoundError: No module named 'flask._compat'
```
Versions of `flask` that are `<=1.0.0` have this module present.
Let's see if this change can fix the issue without further implications.

### CODE REVIEW

**Comment by fridex** [comment]
Did you use Thoth to resolve dependencies?

**Comment by mayaCostantini** [comment]
@fridex Yes

**Comment by fridex** [comment]
It might be a good idea to use Pipenv in this case with `flask<=1.0.0`. Pipenv will resolve the latest possible, Thoth approximates latest.

**Comment by mayaCostantini** [comment]
@fridex this was changed in https://github.com/thoth-station/user-api/pull/1702/commits/b47f9a4e533dc0ab270abfc83cf33a3f699e2565

**Review by fridex — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
