### PR TITLE
Fix 404 for queued requests

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Depends-On: https://github.com/thoth-station/storages/pull/2078
Fixes: https://github.com/thoth-station/thoth-application/issues/568

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
https://github.com/thoth-station/storages/issues/2083

**Review by saisankargochhayat — APPROVED** [review]
Thanks this looks good to me! :+1:

**Comment by saisankargochhayat** [comment]
Do we want to keep these user requests forever? Or clean them up at some point?

**Comment by fridex** [comment]
> Do we want to keep these user requests forever? Or clean them up at some point?

Let's keep them for now... let's see how this adopts. Otherwise we can delete them once the workflow finishes.

**Comment by fridex** [comment]
The update is propagated.

/approve

**Pull request merged**
