### PR TITLE
Provide custom error handlers with more information

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/thoth-station/user-api/pull/245

### CODE REVIEW

**Comment by fridex** [comment]
CI will be fixed with https://github.com/thoth-station/user-api/pull/245/commits/48a0fc8e4031060f3aa3f0824f6564836c194527 once #245 will be merged.

**Comment by goern** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Pull request merged**
