### PR TITLE
Change the order according to openapi

### PR DESCRIPTION
**Pull request by bissenbay**

### CODE REVIEW

**Comment by fridex** [comment]
Is this related to any issue? The order should not be relevant as parameters should be passed as keyword arguments.

**Comment by bissenbay** [comment]
> Is this related to any issue? The order should not be relevant as parameters should be passed as keyword arguments.

I had troubles running package-extract jobs. It wouldn't run and on the logs of user-api we saw there was a missing parameter for image, then I thought this might be because of the order. But, today. I see I can schedule package-extract job, but there is error image pull.

**Comment by fridex** [comment]
> > Is this related to any issue? The order should not be relevant as parameters should be passed as keyword arguments.
> 
> I had troubles running package-extract jobs. It wouldn't get scheduled and on the logs of user-api we saw there was a missing parameter for image, then I thought this might be because of the order. But, today. I see I can schedule package-extract job, but there is error image pull.

It might be related to https://github.com/thoth-station/user-api/pull/623 Could you please check if the issue still persists in our test environment?

**Comment by bissenbay** [comment]
> > > Is this related to any issue? The order should not be relevant as parameters should be passed as keyword arguments.
> > 
> > 
> > I had troubles running package-extract jobs. It wouldn't get scheduled and on the logs of user-api we saw there was a missing parameter for image, then I thought this might be because of the order. But, today. I see I can schedule package-extract job, but there is error image pull.
> 
> It might be related to #623 Could you please check if the issue still persists in our test environment?

Yes, exactly. This is the error I was facing. Thanks a lot! I guess this PR is not relevant and I'm going to close it.

**Pull request closed without merging**
