### PR TITLE
Introduce count and limit on API for advise

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/thoth-station/common/pull/221

### CODE REVIEW

**Comment by fridex** [comment]
We will need to adjust thamos for this.

**Comment by fridex** [comment]
recheck

**Comment by goern** [comment]
> We will need to adjust thamos for this.

Shall we first create the thamos PR or first merge this?!

**Comment by fridex** [comment]
Let's merge this first.

**Comment by fridex** [comment]
I will merge this in order to continue with work.

**Pull request merged**
