### PR TITLE
Parametrize obtaining container images

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/user-api/issues/1541

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... requires new thoth-storages with https://github.com/thoth-station/storages/pull/2507

**Comment by fridex** [comment]
/unhold

Ready to be reviewed.

**Review by pacospace — APPROVED** [review]
💯

**Pull request merged**
